services:
  - type: web
    name: besage-chat-api
    env: python
    plan: free # Or choose a paid plan for production
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn core.asgi:application 
      -k uvicorn.workers.UvicornWorker 
      -b 0.0.0.0:$PORT
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: besage-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: besage-redis
          type: redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: ALLOWED_ORIGINS
        value: "https://besage-frontend.onrender.com,https://your-app-domain.com"

  - type: redis
    name: besage-redis
    ipAllowList: # Required for Redis
      - source: 0.0.0.0/0
        description: Allow all
    plan: free # Or choose a paid plan for production

databases:
  - name: besage-db
    plan: free # Or choose a paid plan for production
