# Generated by Django 5.1.6 on 2025-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
